version: "3.9"

services:

  postgres:
    container_name: my_p_g
    image: postgres:14.0
    environment:
      POSTGRES_DB: "whale-coin"
      POSTGRES_USER: "anton"
      POSTGRES_PASSWORD: "111"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PDB-work/psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  web:
    container_name: my_tomcat
    image: tomcat:9.0.54
    environment:
      DB_URL: "jdbc:postgresql://my_p_g:5432/whale-coin"
      POSTGRES_DB: "whale-coin"
      POSTGRES_USER: "anton"
      POSTGRES_PASSWORD: "111"
    ports:
      - 8081:8080
      - 5005:5005
    volumes:
      - ./Whale-server/build/libs/Whale-server-1.0.war:/usr/local/tomcat/webapps/Whale-server-1.0.war
    restart: always

#  telegram_client:
#    container_name: my_telegram
#    image: 8-jre-bullseye
#    environment:
#      MY_API_ID: "111111"
#      MY_API_HASH: "111111"
#      MY_PHONE: "111111"
#      ID_WHALE_ALERT: "-1001309043988"
#      ADMIN_ID: "1111111"
#    ports:
#      - 5005:5005
#    volumes:
#      - ./Whale-server/build/libs/Whale-server-1.0.war:/usr/local/tomcat/webapps/Whale-server-1.0.war
#    restart: always